version: '3'
services:

  postgres:
    container_name: postgres
    image: postgres:11.5-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/courts-data/postgres:/var/lib/postgresql/data
    env_file: app.env
    restart: on-failure

  app:
    container_name: courts-app
    command: ["python", "app/app.py"]
    build:
      # Set the context to project root so we can pull in core dependencies
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    image: courts-app:latest
    volumes:
      - ./:/src/
    restart: always
    stdin_open: true
    env_file: app.env
    ports:
      - "8000:8000"
    tty: true

  jupyter:
    container_name: courts-jupyter
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --no-browser --NotebookApp.token=''
    build:
      # Set the context to project root so we can pull in core dependencies
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    image: courts-app:latest
    volumes:
      - ./:/src/
    restart: always
    stdin_open: true
    env_file: app.env
    ports:
      - "8888:8888"
    tty: true