version: '3'
services:

  postgres:
    container_name: postgres
    image: postgres:11.5-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/courts-data/postgres:/var/lib/postgresql/data
    env_file: app.env
    restart: on-failure

  app:
    container_name: courts-app
    build:
      # Set the context to project root so we can pull in core dependencies
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    image: courts-app:latest
    volumes:
      - ./:/src/
    restart: always
    stdin_open: true
    env_file: app.env
    ports:
      - "8000:8000"
    tty: true